services:
  # Database (MySQL)
  mysql:
    image: mysql:latest
    container_name: mysql
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: RTBSales
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql-data:/var/lib/mysql

  # Backend Service (Express.js)
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_DATABASE: RTBSales
      WAIT_HOSTS: mysql:3306
    volumes:
      - ./api:/api

  # Frontend Service (React)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./client:/client

volumes:
  mysql-data:
    driver: local